version: '3.8'

services:
  spark-master:
    container_name: spark-master
    build: .
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./spark_app:/opt/bitnami/spark/spark_app
      - C:\Users\${USERNAME}\.kaggle:/home/bitnami/.kaggle
    env_file:
      - .env.spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - KAGGLE_CONFIG_DIR=/home/bitnami/.kaggle 
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - spark-network

  spark-worker:
    container_name: spark-worker
    build: .
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - KAGGLE_CONFIG_DIR=/home/bitnami/.kaggle
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./spark_app:/opt/bitnami/spark/spark_app
      - C:\Users\${USERNAME}\.kaggle:/home/bitnami/.kaggle
    networks:
      - spark-network  

networks:
  spark-network:
